### ISSUE TITLE
`startFileUpload` does not fire

### ISSUE THREAD

**Issue by robrobbins** [Kloudless/file-explorer#10]
`selected` does but the `startFileUpload` does not.

i.e this hits:

    explorer.on("selected", function() {... do stuff });

this does not:

     explorer.on("startFileUpload", function() {... do stuff });

**Comment by vinodc** [comment]
To confirm, the `startFileUpload` event doesn't fire when you select the Computer option and perform an upload?

**Comment by robrobbins** [comment]
why does it have to be the "Computer" option? In my case it is not, it was a dropbox one...

**Comment by vinodc** [comment]
Based on the [earlier discussion](https://github.com/Kloudless/file-explorer/issues/5), we handle `selected` events when files in cloud storage are chosen, since they are not being 'uploaded' by the user. This is different from `success` when, for example, 1000 files are selected. It takes some time to create links for all of them prior to returning the information. This is when the `selected` event becomes useful for your use case (hiding the window so the user doesn't need to wait).

This is the same principle behind the startFileUpload. It fires as soon as the user clicks the primary action button (to upload the files). It fires the event for each file uploaded via the Computer. The final `finishFileUpload` will be followed by the `success` event.

**Comment by robrobbins** [comment]
shit, hate it when i do that (wrong button).

you may want to indicate that in the docs - that `startFileUpload` is "Computer" only.

I can use `selected` for cloud ones

**Comment by vinodc** [comment]
@robrobbins Yup! We'll clarify the docs.

**Comment by vinodc** [comment]
Misc. changes for docs and Saver made in https://github.com/Kloudless/file-explorer/commit/eaa5fba3cbad87ae19f2b3641bd2d38031b5e6a5
