### ISSUE TITLE
Version control on CDN?

### ISSUE THREAD

**Issue by lutherism** [Kloudless/file-explorer#16]
I'm interested to hear if you guys have plans to tag release versions on the CDN? Or if you have a recommended way to manage version dependancies (npm+github?). An official ruby gem or npm module would be preferred for us.

**Comment by vinodc** [comment]
Not at the current time. Since the File Explorer is hosted on Kloudless' website, it will automatically be using the latest version. So having the loader (the CDN JS file) with an accessible version implies that we'd need to host different supported versions for the File Explorer. We've discussed the merits of this internally for some time, but have not prioritized it on our roadmap.

**Comment by vinodc** [comment]
Closing since this feature is unavailable currently.
