### ISSUE TITLE
Switching accounts in saver broken on Chrome

### ISSUE THREAD

**Issue by lutherism** [Kloudless/file-explorer#17]
Transposed from an internally filed bug:

Steps to reproduce:

Open Kloudless Saver.
Associate an account with Dropbox.
Save to Dropbox.
Reopen Kloudless Saver.
Click account switcher dropdown and then click "Accounts".

Expected: Able to pick another account or another cloud service.

Observed: No response.

Note: In the uploader, this isn't happening. You can work around this by clicking on the first dropbox account and then clicking on "Accounts", but it's very unintuitive, and should work directly.

**Comment by vinodc** [comment]
I'm having a little trouble reproducing this. Is it reproducible at http://jsfiddle.net/pseudonumos/PB565/embedded/result/ ? If not, but it's reproducible in your Saver, it might be a particular sequence of method calls that results in the `document.location.hash` of the iframe being set to "#/accounts" without the view updating to the Accounts page. That would cause the symptoms being seen. If it's reproducible on an internal test server that I could get access to, it would be great if you could email me a link to it (vinod@kloudless.com). Thanks.

**Comment by lutherism** [comment]
Sorry for not getting back to this till now.

Yes, I can reproduce this on JSFiddle, following the listed steps exactly. Here's a screenshot of the where it's broken. From that state, if I click the Accounts item in the dropdown, nothing happens.

http://imgur.com/5wAO2uh

**Comment by vinodc** [comment]
Thanks for the update Alex. I'm still encountering some trouble reproducing
here. Could you let me know which browser you were using?

When I re-open the Saver, it opens to the Accounts page rather than the
file explorer page, so the document.location.hash matches the view
currently being displayed and there is no Accounts button to click on.
Could you help me troubleshoot this via the Chrome Inspector? Could you
switch the Inspector's window to point to the explorer.html iframe and then
let me know what `document.location.hash` points to immediately after you
re-open the Explorer and it displays the list of files? Thanks.

**Comment by lutherism** [comment]
It does not pop into the account page for us on any machine if you have an account logged in.

**Comment by lutherism** [comment]
The iframe's document.location.hash is "#/accounts" when I open it while logged in. And I'm taken to the file browsing view.

**Comment by lutherism** [comment]
When I click an account name (as part of the work around) the hash becomes "#/files/59685949"

**Comment by aschiopu** [comment]
@vinodc 

steps to reproduce:
1. visit http://jsfiddle.net/pseudonumos/PB565/embedded/result/
2. click save a file
3. pick dropbox
4. authenticate 
5. click save in order to save the file
6. click `save a file` again (should open up in the dropbox folder)
7. click top left where the account dropdown is .. by default showing you the email. 2 options should come up. The email and "Accounts"
8. Click "Accounts". 

Result: Does nothing. It closes the dropdown but otherwise does nothing.

steps to workaround:
9. Click the accounts dropdown again.
10. This time click on your email. (it will appear like nothing happened- the dropdown closed)
11. Click the accounts dropdown again. 
12. Now Click "Account" and it will work.

**Comment by vinodc** [comment]
Thanks Alexei, Alex. I've reproduced the problem and am working on a
solution. Will keep you updated.

**Comment by vinodc** [comment]
This issue should now be resolved in production. Thanks for your assistance in trouble-shooting it.
