### ISSUE TITLE
Saver doesn't follow HTTP Status Code 30x redirects

### ISSUE THREAD

**Issue by lutherism** [Kloudless/file-explorer#18]
It would be nice if the saver could handle file URLs which may be redirected.

IE

File Explorer gives Kloudless the url "example.com/myFile.pdf" to save
Kloudless requests "example.com/myFile.pdf" and recieves a 302 status code with a "Location: example.com/myActualFile.pdf" header

It would be nice if Kloudless would follow that header to the actual file and save that one.

I don't know if this is feasable, but would be quite useful for hooking up to dynamic file systems.

**Comment by vinodc** [comment]
While we do follow redirects for GET requests (like downloads), uploads generally do not resend POST data on a redirect, since the redirect could be in response to a successful operation rather than a failure. We would not want to resend data on a success since it may not be expected, and even if it is, it may not be idempotent. I believe the HTTP spec does allow for the scenario you describe with a 307 response code, but I doubt the server you are talking about returns that.

**Comment by lutherism** [comment]
Hmm strange. Its failing in this case for me. Maybe because it was getting redirecting twice? The second time to a separate domain.

first response 301, second response 302.

Anyway, we are just using the direct URL now, so it's may not be worth tracking down.

**Comment by vinodc** [comment]
Whoops, I misunderstood and replied too soon. This is the case where the Saver downloads the file and attempts to save it. I'll verify that we follow redirects on downloads for this particular case and get back with an update.

**Comment by lutherism** [comment]
Cool, no problem. Thanks Vinod.

**Comment by vinodc** [comment]
I've been unable to reproduce this. The Saver URL is handled correctly through multiple redirects in my tests (both 301 and 302). If you could provide me with a test URL, I can help troubleshoot further.

**Comment by vinodc** [comment]
Please re-open this issue if you continue to encounter this problem.
