### ISSUE TITLE
Multipart uploads for file saver?

### ISSUE THREAD

**Issue by lutherism** [Kloudless/file-explorer#20]
Is there any plan to have the File Explorer saver support multipart uploads? We can't release with the current 100MB limit.

Thanks Vinod.

**Comment by vinodc** [comment]
Hi Alex. Multipart uploads via the Saver require the destination cloud service the file is being uploaded to to support multipart-uploads. This is because the file is being uploaded to that destination cloud service. At the current time, we've only released this [feature](https://developers.kloudless.com/docs#multipart-upload) for s3 and azure. However, we prioritize new features partly based on demand, so I've made a note that you require this capability.

Were there any services you were looking to release support for sooner rather than later? For example, Box, Google Drive, etc.

**Comment by lutherism** [comment]
Hey Vinod. We would currently like to release with the following services: 
```
['dropbox', 'box', 'gdrive', 'skydrive', 'sharefile', 'copy', 'egnyte']
```

**Comment by lutherism** [comment]
@vinodc Could we get an update on if/when these services will be covered? Thanks Vinod.

**Comment by vinodc** [comment]
@lutherism We will be releasing multipart upload support for file storage services to our on-premises version next month. Our cloud version will have this support generally available following that release, tentatively scheduled for June. Note that `skydrive` and `copy` do not currently support multipart uploads.

**Comment by lutherism** [comment]
OK thank you for the info Vinod.

**Comment by StuartPlanGrid** [comment]
@vinodc I'm a colleague of @lutherism, wondered if June was still on-target for multipart upload to the previously noted services.

**Comment by vinodc** [comment]
@StuartPlanGrid Hi Stuart. This is still on track for early June (either our June 9 or June 16 release).

**Comment by StuartPlanGrid** [comment]
Excellent, thank you.

**Comment by vinodc** [comment]
Checking in with an update.

We are aiming to release on June 16 with support for `egnyte`, `dropbox`, `gdrive`, `skydrive`, `sharepoint`, `onedrivebiz` and `sharefile`.

**Comment by vinodc** [comment]
This feature has been released with support for the services I mentioned in my previous comment, in addition to `s3` and `azure`. Feel free to send any feedback you have our way.

**Comment by stuart-sge** [comment]
That is great, thanks for the update.
