### ISSUE TITLE
Provide a `before` type hook in `Events`

### ISSUE THREAD

**Issue by robrobbins** [Kloudless/file-explorer#5]
Augment the provided `success`, `error` and `cancel` events with some sort of `before` type so that appropriate UI action can be taken. 

Why? With no modal treatment provided users wanting that interaction must roll their own into the chooser (in our case) process. Activating the overlay before calling `choose` and removing it on the provided events. The common scenario is a success, which is good, but in the case of a *large* number of uploads the wait can make for poor UX. Given a hook into the `beforeSend` type of area would be ideal for us as we could dismiss any UI, telling the user to go about their business and we'll notify them when done.

**Comment by chriskuehl** [comment]
Hey @robrobbins, thanks again for the feedback! We just merged and deployed 2dab9def which adds these new events:

* `selected(files)`

  The selected event handler is fired when the user selects files from the
  explorer, but before sending the list to the Kloudless API for additional
  processing. It fires before the `success` handler, and can allow you to
  perform an action while waiting to get the final list.

  If `copy_to_upload_location` and `link` are both false, then this event is
  equivalent to the `success` event (since nothing needs to happen on the
  server after the selections are made), so this event probably isn't useful
  for you.

  `files` is an array of files, formatted the same way as the array passed to
  `success`.

* `startFileUpload(file)`

  Fired when a file upload starts (once per file being uploaded). `file` is an
  object containing keys `id`, `name`, `size`, and `mime_type`.

* `finishFileUpload(file)`

  Fired when a file upload completes successfully (once per file being
  uploaded). `file` contains the same information as in `startFileUpload`
  above.

In particular, `startFileUpload` is the name we gave to the requested `before` hook. Hope these will be helpful, and do let us know if you have any additional feedback!

**Comment by robrobbins** [comment]
perfect

**Comment by robrobbins** [comment]
when will the updated file be avail on https://static-cdn.kloudless.com/p/platform/sdk/kloudless.explorer.js ?

**Comment by vinodc** [comment]
@robrobbins The change was released a few days ago, so it should be live.
