### ISSUE TITLE
Is persistent file access supported?

### ISSUE THREAD

**Issue by JohnWeisz** [Kloudless/file-explorer#59]
First, I would like to say that I'm amazed by the Kloudless file explorer, it is obvious a lot of work has been put into it. However, we are looking for the following functionalities and couldn't find if Kloudless offers it:

 - Read file from path
 - Write file to path
 - Prompt user to pick a file/folder for saving and return the selected file/folder path
 - Prompt user to pick a file/folder for opening and return the selected file/folder path

These 4 parts together enable a seamless cloud storage experience with the same capabilities as native local file access (i.e. once the user opened a file that file is then accessible by our web-app indefinitely). 

**Is this possible through Kloudless?**

-----

For example, opening a file and then reading it later seamlessly in OneDrive is possible through the MSGraph API by doing the following steps:

 1. Make user pick a file using the OneDrive file picker, configured to return metadata about the picked file, most notably its unique `id`
 2. Query the path of this file using its `id`
 3. Store this path

-- user closes, then later re-opens app --

 4. Acquire download link for previously stored path
 5. Download file

**Comment by vinodc** [comment]
@JohnWeisz Thanks for reaching out and for the words of appreciation. 

To clarify, Kloudless does not provide cloud storage itself. Kloudless provides a single cloud storage API that abstracts other cloud storage APIs, including OneDrive, so that your application can integrate with all of them with a single implementation.

The steps you have outlined with OneDrive are possible with the Kloudless File Explorer and [Storage API](https://developers.kloudless.com/docs/v1/storage). File metadata returned from the File Explorer contains a unique ID. The bearer token corresponding to the user's Kloudless account can also be returned with the File Explorer's `retrieve_token` configuration option. This information can be stored by your application. The Storage API can then be accessed at a later time to download the file based on its ID ([docs](https://developers.kloudless.com/docs/v1/storage#files-download-a-file)).

Please feel free to send any other questions you have our way.
