### ISSUE TITLE
Bypass mobile pop-up blocking

### ISSUE THREAD

**Issue by vinodc** [Kloudless/file-explorer#7]
The experience on mobile currently requires the user to disable popup blocking so that the authentication popup may open. However, there is a possibility that popups will not be blocked if it is opened on the direct code path from the event handler rather than after a postMessage to the iframe on the same domain as the API server.

This can be accomplished in two ways:

1. The user could click on a service button within the iframe.
 Each service button would have to be in its own iframe with the appropriate JS/CSS so that clicking them initiates the authentication process. These iframes must be loaded from the same domain as the API server, similar to the /static/iexd.html so it does require some work from the Kloudless team to configure the backend.
 Pros:
 * Better UX since we avoid an extra click.

 Cons:
 * The number of iframes that would have to be loaded increases linearly with the number of services displayed, which makes this more inefficient.

2. Or we need to display a separate UI element after the user clicks a service that requires another click to open the popup.
 For example, it could be implemented as a light-box effect with a confirmation dialog indicating that a pop-up will be opened to connect the service. The iexd.html iframe can be made visible in preparation to display the lightbox, taking up the entirety of the UI, if we're on mobile and feel the open() might fail. If it does indeed fail, the confirmation dialog can display and request the second click.
 Pros:
 * Only a single additional iframe needs to be loaded. 

 Cons:
 * An extra click is required by the mobile user.

I'm leaning towards 2 if the UX experience isn't terrible.

**Comment by chriskuehl** [comment]
bfe85d58d8184adcf3c170f2a21c6f05641bc7a8 fixes this in a transparent way for all supported browsers except IE 9 and 10 by eliminating the use of the iexd iframe entirely.

Due to restrictions on postMessage in IE < 11, we can't avoid it in those browsers, though. I have a fix partially developed for those browsers which is basically option 2 from above. It should be ready soon.

In summary: we can keep the experience the same (and avoid popup blockers) for modern browsers, and make it work with just an extra click on IE < 11. I think this is probably the ideal solution.

**Comment by vinodc** [comment]
Looks like this works. Nice job.

**Comment by chriskuehl** [comment]
e3a48ec3c3 (just merged, not yet deployed) should take care of this on IE as well
